on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: yarn install && yarn pretest 
        env: 
          CI: true
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: eslint
      